services:
   patient-module:
      build: .
      image: patient-module:1.0
      container_name: patient-module
      ports:
         - "5001:5001"
      command: /bin/bash -c "java -jar /app/target/patient.data.exchange-0.0.1-SNAPSHOT.jar"